# Generated by Django 3.0.3 on 2020-09-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
